SELECT USER
FROM DUAL;
--==>> SEMIPJ3

INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('J001','JAVA');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('S001','SPRING');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('JS001','JavaScript');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('O001','ORACLE');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('H001','HTML');

INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('JAVA001','자바의정석','도우출판');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('JAVA002','코딩은 처음이라 with 자바','영진닷컴');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('PYTHON001','프로젝트로 배우는 파이썬 프로그래밍','학산미디어');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('SPRING001','스프링 프레임워크 첫걸음','위키북스');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('SPRING002','스프링 부트핵심가이드','위키북스');








