SELECT USER
FROM DUAL;
--==>> SEMIPJ3

INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('J001','JAVA');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('S001','SPRING');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('JS001','JavaScript');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('O001','ORACLE');
INSERT INTO SUBJECT_NAME(SUB_CODE, SUB_NAME) VALUES('H001','HTML');

INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('JAVA001','자바의정석','도우출판');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('JAVA002','코딩은 처음이라 with 자바','영진닷컴');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('PYTHON001','프로젝트로 배우는 파이썬 프로그래밍','학산미디어');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('SPRING001','스프링 프레임워크 첫걸음','위키북스');
INSERT INTO TEXTBOOK(TB_CODE, TB_NAME, PUB) VALUES('SPRING002','스프링 부트핵심가이드','위키북스');



INSERT INTO OPENED_SUBJECT(OS_CODE, OS_START, OS_END, OS_DATE, OS_PT, OS_WT, OS_ATT, TB_CODE, PROF_ID, SUB_CODE, OC_CODE)
VALUES('OS002',TO_DATE('2021-08-07','YYYY-MM-DD'),TO_DATE('2021-12-17','YYYY-MM-DD'),TO_DATE('2020-12-17','YYYY-MM-DD'),40,30,30,'JAVA001','hangeul97','H001','H1');

INSERT INTO OPENED_SUBJECT(OS_CODE, OS_START, OS_END, OS_DATE, OS_PT, OS_WT, OS_ATT, TB_CODE, PROF_ID, SUB_CODE, OC_CODE)
VALUES('OS001',TO_DATE('2021-06-07','YYYY-MM-DD'),TO_DATE('2021-09-07','YYYY-MM-DD'),TO_DATE('2021-04-17','YYYY-MM-DD'),30,40,30,'PYTHON001','hungryman','O001','H2');

INSERT INTO OPENED_SUBJECT(OS_CODE, OS_START, OS_END, OS_DATE, OS_PT, OS_WT, OS_ATT, TB_CODE, PROF_ID, SUB_CODE, OC_CODE)
VALUES('OS004',TO_DATE('2022-01-07','YYYY-MM-DD'),TO_DATE('2022-08-25','YYYY-MM-DD'),TO_DATE('2021-12-17','YYYY-MM-DD'),50,30,20,'SPRING001','mmm1234','JS001','H3');

INSERT INTO OPENED_SUBJECT(OS_CODE, OS_START, OS_END, OS_DATE, OS_PT, OS_WT, OS_ATT, TB_CODE, PROF_ID, SUB_CODE, OC_CODE)
VALUES('OS003',TO_DATE('2022-09-07','YYYY-MM-DD'),TO_DATE('2022-10-30','YYYY-MM-DD'),TO_DATE('2022-03-18','YYYY-MM-DD'),NULL,NULL,NULL,'SPRING001','javagosu','JS001','H3');


DESC GRADE;
