SELECT USER
FROM DUAL;
--==>> SEMIPJ3
SELECT *
FROM GRADE;

-- 성적 테이블
CREATE TABLE GRADE 
( GRADE_CODE       VARCHAR2(10)       NOT NULL                      -- 성적코드
, GRADE_DATE       DATE               DEFAULT SYSDATE               -- 평가날짜
, GRADE_ATT       NUMBER(3)                                         -- 출결
, GRADE_WT       NUMBER(3)                                          -- 필기
, GRADE_PT       NUMBER(3)                                          -- 실기
, OS_CODE       VARCHAR2(10)       NOT NULL                         -- 개설과목코드
, APP_CODE       VARCHAR2(10)       NOT NULL                        -- 수강신청코드
, CONSTRAINT GRADE_GRADE_CODE_PK PRIMARY KEY(GRADE_CODE)
);

ALTER TABLE GRADE
ADD CONSTRAINT GRADE_OS_CODE_FK FOREIGN KEY (OS_CODE)
    REFERENCES OPENED_SUBJECT(OS_CODE);


ALTER TABLE GRADE
ADD CONSTRAINT GRADE_APP_CODE_FK FOREIGN KEY (APP_CODE)
    REFERENCES APP(APP_CODE);


-- EXEC PRC_GRADE_UPDATE (성적코드, 출결, 필기, 실기)


EXEC PRC_GRADE_UPDATE('A20001', '80', '80','70');
--==>> PL/SQL 프로시저가 성공적으로 완료되었습니다.

SELECT *
FROM GRADE;


EXEC PRC_GRADE_UPDATE('OS002', '80', '80','70');

SELECT *
FROM GRADE;


-- 성적 테이블 데이터 입력 
INSERT INTO GRADE (GRADE_CODE, GRADE_DATE, GRADE_ATT, GRADE_WT, GRADE_PT, OS_CODE, APP_CODE)
VALUES('OS002', SYSDATE, 30, 40, 30,'AP1102','PO1021');  

-- 개설목코드,수강신청코드 OS_CODE, APP_CODE
EXEC PRC_GRADE_INSERT('OS002','H1',80,40,30);

SELECT *
FROM APP;


DESC APP


INSERT INTO APP (APP_CODE, APP_DATE, STU_ID, OC_CODE) VALUES ('G301', SYSDATE, '20171305', 'H1');
INSERT INTO APP (APP_CODE, APP_DATE, STU_ID, OC_CODE) VALUES ('G302', SYSDATE, '20153075', 'H2');
INSERT INTO APP (APP_CODE, APP_DATE, STU_ID, OC_CODE) VALUES ('G303', SYSDATE, '20143054', 'H3');
INSERT INTO APP(APP_CODE, STU_ID, OC_CODE) VALUES ('A101','20153075','H1');
INSERT INTO APP(APP_CODE, STU_ID, OC_CODE) VALUES ('A102','20161062','H2');












