SELECT USER
FROM DUAL;
--==>> SEMIPJ3




-- 학생 테이블 생성
-- ⒫학생ID, 비밀번호, 학생이름, 등록날짜
CREATE TABLE STUDENT
( STU_ID    VARCHAR2(20)
, STU_PW	    CHAR(7)
, STU_NAME	VARCHAR2(30)	
, STU_DATE  DATE    DEFAULT SYSDATE  -- DEFAULT ?
, CONSTRAINT STUDENT_STU_ID_PK PRIMARY KEY(STU_ID)
);

-- 중도탈락 테이블 생성
-- ⒫중도탈락코드, 중도탈락일자, 수강신청코드, 탈락사유코드
CREATE TABLE QUITLIST
( QUIT_CODE	VARCHAR2(10)
, QUIT_DATE DATE 	DEFAULT SYSDATE  -- DEFAULT ?	
, APP_CODE 	VARCHAR2(10)
, QR_CODE 	VARCHAR2(10)
, CONSTRAINT QUITLIST_QUIT_CODE_PK PRIMARY KEY(QUIT_CODE)
);

ALTER TABLE QUITLIST 
ADD CONSTRAINT APPLICATION_APP_CODE_FK FOREIGN KEY (APP_CODE)       
                REFERENCES APPLICATION(APP_CODE);

ALTER TABLE QUITLIST 
ADD CONSTRAINT QUITREASON_QR_CODE_FK FOREIGN KEY (QR_CODE)       
                REFERENCES APPLICATION(QR_CODE);


-- 중도탈락 사유 테이블 생성
-- ⒫탈락사유코드, 중도탈락사유
CREATE TABLE QUIT_REASON
( QR_CODE 	    VARCHAR2(10)	
, QUIT_REASON	VARCHAR2(40)
, CONSTRAINT QUIT_REASON_PK PRIMARY KEY(QR_CODE)
);

-- 교수자 테이블
CREATE TABLE PROFESSOR
( PROF_ID       	VARCHAR2(20)    -- 교수ID
, PROF_PW       CHAR(7)		    -- 비밀번호
, PROF_NAME     	VARCHAR2(30)	    -- 교수명
, PROF_DATE     DATE	            -- 등록날짜
, CONSTRAINT PROFESSOR_PROF_ID_PK PRIMARY KEY(PROF_ID)
);